// NEXT PLAYER FUNCTION IS USED TO DETERMINE THE NEXT PLAYER
function NextPlayer(squares) {

  return squares.filter(Boolean).length % 2 === 0 ? "X" : "O";
  // ONE PLAYER CLICKS ON A SQUARE AND THEY ARE "X", THEN THE NEXT ONE WHO PICK A SQUARE IS AN "O".

    // THIS FUNCTION USES A FILTER TO ALTERNATE TRUE/FALSE BOOLEAN VALUES.
  // BY THEIR LENGTH, THEN USES MODULES TO DETERMINE IF 
}

export default NextPlayer;
// EXPORT ALLOWS THIS FUNCTION TO BE UTILIZED BY OTHER REACT COMPONENTS
